# Generated by Django 4.2.1 on 2023-05-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_game_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='img_url',
            field=models.URLField(),
        ),
    ]
