# Generated by Django 4.2.1 on 2023-05-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_pokemon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='img_url',
            field=models.URLField(null=True),
        ),
    ]
